load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

cc_binary(
    name = "sky",
    srcs = ["viewer.cpp"],
    deps = [
        "//engine/app",
        "//engine/geometry",
        "//engine/platform",
        "//engine/render",
        "//engine/text:ui",
    ],
)
