load("@rules_cc//cc:defs.bzl", "cc_test")

package(default_visibility = ["//visibility:public"])

cc_test(
    name = "frames_test",
    srcs = ["main.cpp"],
    target_compatible_with = ["@platforms//os:macos"],
    deps = [
        "//engine/render",
        "//engine/rhi",
        "//engine/core",
        "//engine/scene",
    ],
)
